name: Synapse New

on:
    workflow_dispatch:
env:
    subscriptionId: ${{secrets.ARM_SUBSCRIPTION_ID}}
    clientId: ${{secrets.ARM_CLIENT_ID}}
    clientSecret:  ${{secrets.ARM_CLIENT_SECRET}}
    tenantId: ${{secrets.ARM_TENANT_ID}}
    resourceGroup: 'rg-testing-uat-001'
    workspacename: 'synw-testing-uat-001'
    
jobs:
    release:
        # You also can use the self-hosted runners.
        runs-on: ubuntu-latest
        steps:
        # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it.
        - uses: actions/checkout@v2
        - uses: Azure/Synapse-workspace-deployment@V1.7.0
          with:
            clientId: ${{env.clientId}}
            clientSecret:  ${{env.clientSecret}}
            subscriptionId: ${{env.subscriptionId}}
            tenantId: ${{env.tenantId}}
            TargetWorkspaceName: ${{env.workspacename}}
            resourceGroup: ${{env.workspacename}}
            TemplateFile: './Azure-Test-1-workspace_publish/synw-testing-dev-001/TemplateForWorkspace.json'
            ParametersFile: './Azure-Test-1-workspace_publish/synw-testing-dev-001/TemplateParametersForWorkspace.json'
            OverrideArmParameters: ''
            environment: 'Azure Public'
            DeleteArtifactsNotInTemplate: 'true'
            managedIdentity: 'False'
            operation: 'deploy'
