name: Synapse Old
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
env:
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Install azure-cli
  # You may pin to the exact commit or the version.
  # uses: pietrobolcato/install-azure-cli-action@f01ae8ab9274a69a854ef40018c9686d60d4891e
      uses: pietrobolcato/install-azure-cli-action@v1
    - name: Login to Azure
      run: |
         az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
         az account set --subscription $ARM_SUBSCRIPTION_ID
    - name: Deploy Synapse Workspace
      run: |
          az deployment group create --name synw-testing-uat-001 --resource-group rg-testing-uat-001  --template-file "./Synapse/TemplateForWorkspace.json"  --template-file "./Synapse/TemplateForWorkspace.json" --parameters  "./Synapse/TemplateParametersForWorkspace.json"  --mode Incremental  
           
           
     