name: Synapse New

on:
    workflow_dispatch:
env:
    subscriptionId: ${{secrets.SUBSCRIPTIONID}}
    clientId: ${{secrets.CLIENTID}}
    clientSecret:  ${{secrets.CLIENTSECRET}}
    tenantId: ${{secrets.TENANTID}}
    resourceGroup: 'rg-testing-uat-001'
    workspacename: 'synw-testing-uat-001'
    
jobs:
    release:
        # You also can use the self-hosted runners.
        runs-on: ubuntu-latest
        steps:
        # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it.
        - uses: actions/checkout@v2
        - uses: azure/synapse-workspace-deployment@release-1.0
          with:
            clientId: ${{env.clientId}}
            clientSecret:  ${{env.clientSecret}}
            subscriptionId: ${{env.subscriptionId}}
            tenantId: ${{env.tenantId}}
            TargetWorkspaceName: ${{env.workspacename}}
            resourceGroup: ${{env.workspacename}}
            TemplateFile: './synw-testing-dev-001/TemplateForWorkspace.json'
            ParametersFile: './synw-testing-dev-001/TemplateParametersForWorkspace.json'
            OverrideArmParameters: ''
            environment: 'UAT'
            DeleteArtifactsNotInTemplate: 'true'
            managedIdentity: 'False'
            operation: 'deploy'
