name: Synapse release to UAT

on:
    workflow_dispatch:
jobs:
    release:
        # You also can use the self-hosted runners.
        runs-on: ubuntu-latest
        steps:
        # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it.
        - uses: actions/checkout@v2
        - uses: azure/synapse-workspace-deployment@release-1.0
        with:
          TargetWorkspaceName: 'synw-testing-uat-001'
          TemplateFile: './synw-testing-dev-001/TemplateForWorkspace.json'
          ParametersFile: './synw-testing-dev-001/TemplateParametersForWorkspace.json'
          OverrideArmParameters: './path of the parameters.yaml'
          environment: 'UAT'
          resourceGroup: 'rg-testing-uat-001'
          clientId: ${{secrets.CLIENTID}}
          clientSecret:  ${{secrets.CLIENTSECRET}}
          subscriptionId: ${{secrets.SUBSCRIPTIONID}}
          tenantId: ${{secrets.TENANTID}}
          DeleteArtifactsNotInTemplate: 'true'
          managedIdentity: 'False'
