name: Synapse New

on:
    workflow_dispatch:
env:
    ARM_SUBSCRIPTION_ID: ${{secrets.ARM_SUBSCRIPTION_ID}}
    ARM_CLIENT_ID: ${{secrets.ARM_CLIENT_ID}}
    ARM_CLIENT_SECRET:  ${{secrets.ARM_CLIENT_SECRET}}
    ARM_TENANT_ID: ${{secrets.ARM_TENANT_ID}}
    resourceGroup: 'rg-testing-uat-001'
    workspacename: 'synw-testing-uat-001'
    
jobs:
    release:
        # You also can use the self-hosted runners.
        runs-on: ubuntu-latest
        steps:
        # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it.
        - uses: actions/checkout@v2
        - uses: azure/synapse-workspace-deployment@v1.6.0
          with:
            clientId: ${{secrets.ARM_CLIENT_ID}}
            clientSecret:  ${{secrets.ARM_CLIENT_SECRET}}
            subscriptionId: ${{secrets.ARM_SUBSCRIPTION_ID}}
            tenantId: ${{secrets.ARM_TENANT_ID}}
            TargetWorkspaceName: ${{secrets.workspacename}}
            resourceGroup: ${{secrets.workspacename}}
            TemplateFile: './synw-testing-dev-001/TemplateForWorkspace.json'
            ParametersFile: './synw-testing-dev-001/TemplateParametersForWorkspace.json'
            OverrideArmParameters: ''
            # environment: 'UAT'
            DeleteArtifactsNotInTemplate: 'true'
            managedIdentity: 'False'
            operation: 'deploy'
        
